sudo: required
services: 
  - docker
before_install:
  - docker build -t sweber8211/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true sweber8211/docker-react npm run test
deploy:
  edge: true
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-west-1-455616434489"
  bucket_path: "docker-react"
  on:
    branch: main
access_key_id: $AWS_ACCESS_KEY
secret_access_key: $AWS_SECRET_KEY